s += 1
fire = instance_create(((global.idealborder[0] + ((global.idealborder[1] - global.idealborder[0]) / 2)) + (cos((off / 6)) * 20)), (130 + (sin((off / 6)) * 10)), obj_sinefire_asghelix)
fire.sf = 4
fire.vspeed = 4
fire.s = s
side += 1
if (side >= 4)
    side = choose(-2, -1)
if (side <= 1)
    fire.sv = 11
if (side >= 1)
    fire.sv = -11
alarm[0] = 5
off += 1
fire.vspeed += (sin((off / 6)) * 0.2)
