instance_destroy()
cl = 0
if (room == room_fire5 && FL_HotlandBattleProgressCounter > 0)
	instance_destroy()
if (room == room_fire7 && FL_HotlandBattleProgressCounter > 1)
	instance_destroy()
if (room == room_fire_walkandbranch && FL_HotlandBattleProgressCounter > 2)
	instance_destroy()
if (room == room_fire_walkandbranch2 && FL_HotlandBattleProgressCounter > 3)
	instance_destroy()
if (room == room_fire_preshootguy4 && FL_HotlandBattleProgressCounter > 4)
	instance_destroy()
if (FL_DisableRandomEncounters == true || FL_TruePacifist == true)
	instance_destroy()
