draw_sprite_ext(sprite_index, image_index, x, y, 2, 2, 0, image_blend, 1)
if (shock == 0)
    draw_sprite_ext(spr_sadgore_face, face, (x + 122), (y - 30), 2, 2, 0, c_white, 1)
if (shock == 1)
    draw_sprite_ext(spr_asgore_shockface, 0, (x + 122), (y - 30), 2, 2, 0, c_white, 1)
