myinteract = 3
global.msc = 0
global.typer = 5
global.facechoice = 0
global.faceemotion = 0
global.msg[0] = "* That skeleton over there&  just told me how to dodge&  \"orange attacks.\"/"
global.msg[1] = "* What did he say...?&* Something like.../"
global.msg[2] = "* \"Traffic lights have three&  lights on them.\"/"
global.msg[3] = "* \"The third light^1, the green&  one^1, means GO.\"/"
global.msg[4] = "* \"The first light^1, the red&  one^1, means STOP.\"/"
global.msg[5] = "* \"The second light^1, the yellow&  one^1, means YIELD.\"/"
global.msg[6] = "* \"In order to dodge an&  orange attack^1, you must&  be moving.\"/"
global.msg[7] = "* \"So^1, just think of it&  this way...\"/"
global.msg[8] = "* \"Red and yellow lights together&  make orange.\"/"
global.msg[9] = "* \"Then you obey the rule&  of the leftover green&  light^1, which means GO.\"/"
global.msg[10] = "* \"Easy^1, huh?\"/"
global.msg[11] = "* \"Just think of a red and yellow&  traffic light which is&  actually green.\"/"
global.msg[12] = "* Yeah.../"
global.msg[13] = "* Then he started talking about&  plaid attacks.../%%"
mydialoguer = instance_create(0, 0, obj_dialoguer)
talkedto += 1
