scr_monstersetup()
dmg = global.monsteratk[myself]
image_speed = 0
part1 = obj_sorrybody
mypart1 = instance_create((x + 100), (y + 40), part1)
part1.dmg = dmg
alarm[9] = 8
hurtanim = 0
hurtsound = snd_nosound
talked = false
whatiheard = -1
attacked = 0
killed = 0
global.heard = 0
takedamage = 0
mercymod = -9999
sha = 0
shb = 0
ht = 100
wd = 200
myplot = 0
hitplot = 0
prevhp = global.monsterhp[myself]
goodot = 0
d_con = 0
p_con = 0
p_mode = 0
n_con = 0
