myinteract = 3
global.typer = 17
global.facechoice = 3
global.msc = 0
global.msg[0] = "\\E0* hey there.&* this is just a little test./"
global.msg[1] = "\\TS \\F0 \\F4 \\TP %"
global.msg[2] = "I WILL BATHE IN&A SHOWER OF KISSES&EVERY MORNING !/"
global.msg[3] = "\\TS \\F0 \\F3 \\Ts %"
global.msg[4] = "* no^1. not today./%%"
global.faceemotion = 0
mydialoguer = instance_create(0, 0, obj_dialoguer)
