image_alpha = 0
maxalpha = 1
timer = 0
vspeed = (1 + random(2))
alarm[0] = 4
depth = -2
size = (random(0.5) + 0.5)
image_xscale = size
image_yscale = size
rotspeed = (3 + floor(random(5)))
image_speed = 0
