draw_set_color(c_white)
draw_text(100, 100, string_hash_to_newline("INSTRUCTIONS ROOM.# #YOU WILL ENCOUNTER A SERIES OF ATTACK.# #PRESS [Z] TO FIRE THE WEAPON.# #YOU CAN TEST WEAPON HERE.#SPECIAL RULE:#BLUE LASERS WILL NOT HURT YOU IF YOU ARE STANDING STILL.##PRESS [SPACEBAR] TO CONTINUE."))
