mycoordx = 0
mycoordy = 3
moving = false
checkx = 0
checky = 0
prevx = x
prevy = y
electrocute = 0
orange = -1
green = 0
sprite_index = spr_maincharar
wblend = c_white
oblend = old_make_color_hsv(17, 83, 255)
yblend = old_make_color_hsv(45, 128, 255)
tileid = 0
pir = 0
dog = 0
