con = 1
FL_CookedNoodles = true
global.msg[1] = scr_gettext("obj_instantnoodleitem_30")
global.msg[2] = scr_gettext("obj_instantnoodleitem_31")
global.msg[3] = scr_gettext("obj_instantnoodleitem_32")
global.msg[4] = scr_gettext("obj_instantnoodleitem_33")
global.msg[5] = scr_gettext("obj_instantnoodleitem_34")
global.msg[6] = scr_gettext("obj_instantnoodleitem_35")
global.msg[7] = scr_gettext("obj_instantnoodleitem_36")
global.msg[8] = scr_gettext("obj_instantnoodleitem_37")
global.msg[9] = scr_gettext("obj_instantnoodleitem_38")
global.msg[10] = scr_gettext("obj_instantnoodleitem_39")
global.msg[11] = scr_gettext("obj_instantnoodleitem_40")
global.msg[12] = scr_gettext("obj_instantnoodleitem_41")
global.msg[13] = scr_gettext("obj_instantnoodleitem_42")
global.msg[14] = scr_gettext("obj_instantnoodleitem_43")
global.msg[15] = scr_gettext("obj_instantnoodleitem_44")
scr_writetext(0, scr_gettext("obj_instantnoodleitem_45"), 0, 0)
