scr_monstersetup(0, 0, 0, 0, 0)
image_speed = 0
part1 = obj_mandogbody
part2 = obj_mandogax
mypart1 = instance_create(x, y, part1)
mypart2 = instance_create(x, y, part2)
hurtanim = 0
hurtsound = snd_doghurt1
talked = false
whatiheard = -1
attacked = 0
killed = 0
global.heard = 0
takedamage = 0
mercymod = -999
joketold = 0
smell = 0
axhp = global.hp
ht = sprite_height
wd = sprite_width
