rotspeed = 38
image_alpha = 0
offsetdir = point_direction(x, y, (obj_heart.x + 8), (obj_heart.y + 8))
image_angle = (offsetdir + 20)
direction = offsetdir
speed = 4
friction = 0.2
dmg = 11
deactivate = 0
timer = 0
fade = 0
