scr_monstersetup()
image_speed = 0
part1 = obj_doodlebug_body
mypart1 = instance_create(x, y, part1)
alarm[9] = 8
hurtanim = 0
hurtsound = snd_nosound
talked = false
whatiheard = -1
attacked = 0
killed = 0
global.heard = 0
takedamage = 0
mercymod = -900
sha = 0
shb = 0
ht = 100
wd = 100
specialmessage = 0
