myinteract = 3
global.msc = 0
global.typer = 5
global.facechoice = 0
global.faceemotion = 0
global.msg[0] = "* Hey^1, shrimp^1!&* You look like you get your&  butt kicked a lot!/"
global.msg[1] = "* Why don't you check out&  my new book on fighting&  in the library?/"
global.msg[2] = "* That is..^1.&* If you're tough enough to&  love reading books!/"
global.msg[3] = "* GROWL!!/%%"
mydialoguer = instance_create(0, 0, obj_dialoguer)
talkedto += 1
