myinteract = 3
global.msc = 505
global.typer = 5
global.facechoice = 0
global.faceemotion = 0
mydialoguer = instance_create(0, 0, obj_dialoguer)
if (conversation != 9)
    conversation += 1
global.interact = 1
