global.batmusic = caster_load("music/xpart_a.ogg")
global.batmusic2 = caster_load("music/xpart_b.ogg")
caster_play(global.batmusic, 1, 0.85)
memtimer = 0
image_alpha = 0
on = 1
image_speed = 0
rev_alpha = 0
xtimer = 0
global.inbattle = true
active = true
