if (mercymod < 100)
{
    blcon = instance_create((x + 140), y, obj_blconsm)
    gg = floor(random(3))
    mycommand = round(random(100))
    with (OBJ_WRITER)
        instance_destroy()
    global.msg[1] = scr_gettext("obj_reaperbird_160")
    global.typer = 2
    global.msg[0] = scr_gettext("obj_reaperbird_165")
    if (mycommand < 75)
        global.msg[0] = scr_gettext("obj_reaperbird_166")
    if (mycommand < 50)
        global.msg[0] = scr_gettext("obj_reaperbird_167")
    if (mycommand < 25)
        global.msg[0] = scr_gettext("obj_reaperbird_168")
    blconwd = instance_create((blcon.x + 15), (blcon.y + 10), OBJ_NOMSCWRITER)
    mycommand = round(random(100))
    global.msg[0] = scr_gettext("obj_reaperbird_177")
    if (mycommand < 75)
        global.msg[0] = scr_gettext("obj_reaperbird_178")
    if (mycommand < 50)
        global.msg[0] = scr_gettext("obj_reaperbird_179")
    if (mycommand < 25)
        global.msg[0] = scr_gettext("obj_reaperbird_180")
    blconwd = instance_create((blcon.x + 15), (blcon.y + 10), OBJ_NOMSCWRITER)
    mycommand = round(random(100))
    global.msg[0] = scr_gettext("obj_reaperbird_187")
    if (mycommand < 75)
        global.msg[0] = scr_gettext("obj_reaperbird_188")
    if (mycommand < 50)
        global.msg[0] = scr_gettext("obj_reaperbird_189")
    if (mycommand < 25)
        global.msg[0] = scr_gettext("obj_reaperbird_190")
    blconwd = instance_create((blcon.x + 15), (blcon.y + 10), OBJ_NOMSCWRITER)
}
else
{
    blcon = instance_create((x + 140), y, obj_blconsm)
    gg = floor(random(3))
    mycommand = round(random(100))
    with (OBJ_WRITER)
        instance_destroy()
    global.msg[1] = scr_gettext("obj_reaperbird_202")
    global.typer = 2
    global.msg[0] = scr_gettext("obj_reaperbird_205")
    blconwd = instance_create((blcon.x + 15), (blcon.y + 10), OBJ_NOMSCWRITER)
    blcon = instance_create((x + 140), (y + 110), obj_blconsm)
    gg = floor(random(3))
    mycommand = round(random(100))
    global.msg[1] = scr_gettext("obj_reaperbird_214")
    global.typer = 2
    global.msg[0] = scr_gettext("obj_reaperbird_217")
    blconwd = instance_create((blcon.x + 15), (blcon.y + 10), OBJ_NOMSCWRITER)
    mycommand = round(random(100))
    blcon = instance_create((x + 250), y, obj_blconsm)
    gg = floor(random(3))
    mycommand = round(random(100))
    global.msg[1] = scr_gettext("obj_reaperbird_229")
    global.typer = 2
    global.msg[0] = scr_gettext("obj_reaperbird_232")
    blconwd = instance_create((blcon.x + 15), (blcon.y + 10), OBJ_NOMSCWRITER)
}
mypart1.stretchup = 1
global.border = 5
obj_heart.x = (round(((global.idealborder[0] + global.idealborder[1]) / 2)) - 8)
obj_heart.y = (round(((global.idealborder[2] + global.idealborder[3]) / 2)) - 8)
