siner = random(360)
size = 1
halfsies = 0
ssx = ((sin((siner / 3)) * 3) * image_xscale)
ssy = (cos((siner / 3)) * 3)
if (y <= 130)
    halfsies = 1
if (y >= 190)
    halfsies = 2
maxer = 0
size = (maxer + (sin((siner / 2)) * 0.02))
