draw_sprite_ext(sprite_index, image_index, x, y, 2, 2, 0, c_white, 1)
if (shock == 0)
    draw_sprite_ext(spr_papyrushead_variety, face, (x + 40), (y - 2), 2, 2, 0, c_white, 1)
if (shock == 1)
    draw_sprite_ext(spr_papface_fatal, 0, (x + 40), (y - 2), 2, 2, 0, c_white, 1)
