// These objects have spr_event, spr_event_small or spr_event_vsmall
// attached to them
global.decomp_triggers_to_show = [
	obj_alphysconveyor,
	obj_alphysfollow_event,
	obj_alphystrigger1,
	obj_alphystrigger2,
	obj_asgore_prebarrier_event,
	obj_asgoremeet_event,
	obj_autowater,
	obj_bouncedown,
	obj_bounceright,
	obj_bounceup,
	obj_boysnightout,
	obj_chipdoor_trigger,
	obj_conveyord,
	obj_conveyorl,
	obj_conveyorr,
	obj_conveyoru,
	obj_cookshowevent,
	obj_core_enemyevent,
	obj_core_enemyevent2,
	obj_countermiddle,
	obj_darksanstrigger,
	obj_dogetrigger1,
	obj_dogringbell,
	obj_dummytrigger,
	obj_encountertrigger1,
	obj_fakesanstrigger,
	obj_floweytrigger,
	obj_floweytrigger2,
	obj_forcedright,
	// obj_friendc_event, // this one also breaks for some reason
	obj_golfedge,
	obj_holedown2,
	obj_iceevent,
	obj_iceeventx4,
	obj_indryspot,
	obj_insidiousconveyor,
	obj_inwaterspot,
	obj_killerboysnightout_event,
	obj_killerlab_event,
	obj_kitchenforcefield,
	// obj_labelevator_b, // this one breaks for some reason
	obj_lastsans_trigger,
	obj_lazyencounterer,
	obj_lazyencounterer_core,
	obj_magicglass_personal,
	obj_mettboss_event,
	obj_mettdestroyed_event,
	obj_mettmilk,
	obj_mettnewsevent,
	obj_monsterkidtrigger1,
	obj_monsterkidtrigger2,
	obj_monsterkidtrigger3,
	obj_monsterkidtrigger4,
	obj_monsterkidtrigger5,
	obj_monsterkidtrigger6,
	obj_monsterkidtrigger7,
	obj_monsterkidtrigger8,
	obj_napstablookdate,
	obj_napstablookfriendtrigger,
	obj_notify_room,
	obj_onionsan_event,
	obj_otherphonecall,
	obj_outsideworld_event,
	obj_papyrus1,
	obj_papyrus2,
	obj_papyrus3,
	obj_papyrus4,
	obj_papyrus5,
	obj_papyrus6,
	obj_papyrus7,
	obj_papyrus8,
	obj_phonecall_room,
	obj_playmovement,
	obj_plotwall1,
	obj_plotwall2,
	obj_plotwall3,
	obj_plotwall4,
	obj_plotwall5,
	obj_plotwall6,
	obj_plotwall_room,
	obj_pofftrigger,
	obj_powerlaser_event,
	obj_precore_event,
	obj_puzzlewall1,
	obj_puzzlewall2,
	obj_sansbasemententer,
	obj_sansbyetrigger,
	obj_sansdate3,
	obj_shyrentrigger,
	obj_sideconveyorl,
	obj_slowdownwalk,
	obj_slowdownwalk_x,
	obj_songwriter,
	obj_specialdrophole,
	obj_spidertalkevent,
	obj_story_engager,
	obj_superdrophole,
	obj_switchhelptrigger,
	obj_theend_forcefield,
	obj_tordogcall,
	obj_torielcall1,
	obj_torielcall2,
	obj_torielcall3,
	obj_torielcall4,
	obj_torielcall5,
	obj_torieltrigger1,
	obj_torieltrigger10,
	obj_torieltrigger11,
	obj_torieltrigger12,
	obj_torieltrigger2,
	obj_torieltrigger3,
	obj_torieltrigger4,
	obj_torieltrigger5,
	obj_torieltrigger6,
	obj_torieltrigger7,
	obj_torieltrigger8,
	obj_torieltrigger9,
	obj_trigger_room,
	obj_triswitchevent,
	obj_true_antiwaver,
	obj_underground_exit,
	obj_undyne1,
	// obj_undyne1_old,
	obj_undyne_blockwrecker,
	obj_undyne_lettercall,
	obj_undynedate_afterward,
	obj_undyneencounter1,
	obj_undyneencounter2,
	obj_undyneencounter3,
	obj_undyneencounter4,
	obj_undynetrigger_boss,
	obj_undynetrigger_boss2,
	obj_undynetrigger_dry,
	obj_warrior_event,
	obj_water_doomreminder,
	obj_waterspot,
	obj_wrongnumbersong
];

function cmd_trigger_show()
{
	obj_decomp_console.show_triggers = !obj_decomp_console.show_triggers;
	
	var enabled = obj_decomp_console.show_triggers;
	command_writeline($"Triggers are now {enabled ? "visible" : "hidden"}.");
	apply_trigger_show();
}

function apply_trigger_show()
{
	for (var i = 0; i < array_length(global.decomp_triggers_to_show); i++)
	{
		if (instance_exists(global.decomp_triggers_to_show[i]))
		{
			global.decomp_triggers_to_show[i].visible = obj_decomp_console.show_triggers;
		}
	}
}