siner = 0
eyetimer = 0
eye_on = 0
slashno = 0
movetype = 0
larm = instance_create((x + 64), (y + 78), obj_npc_marker)
larm.sprite_index = spr_undynex_leftarm
larm.image_xscale = 2
larm.image_yscale = 2
larm.depth = 7
arm_v = 0
larm.visible = false
facetype = 0
heady = 0
pause = 0
shakify = 0
