global.entrance = 24
instance_create(0, 0, obj_persistentfader)
if (room == room_ruins12)
	room_goto(room_ruins13)
if (room == room_ruins13)
	room_goto(room_ruins12)
if (room == room_ruins15E)
	room_goto(room_ruins15A)
if (room == room_ruins16)
	room_goto(room_ruins19)
if (room == room_ruins19)
	room_goto(room_ruins16)
if (room == room_torhouse1)
{
	if (FL_TruePacifist == false)
		caster_free(global.currentsong2)
	room_goto(room_basement1)
}
if (room == room_basement1)
	room_goto(room_torhouse1)
if (room == room_torhouse2)
	room_goto(room_kitchen)
if (room == room_kitchen)
	room_goto(room_torhouse2)
if (room == room_castle_trueexit)
	room_goto(room_castle_prebarrier)
if (room == room_castle_finalshoehorn)
	room_goto(room_castle_throneroom)
if (room == room_castle_throneroom)
	room_goto(room_castle_finalshoehorn)
if (room == room_asghouse2)
	room_goto(room_kitchen_final)
if (room == room_kitchen_final)
	room_goto(room_asghouse2)
if (room == room_tundra_town)
	room_goto(room_tundra_town2)
if (room == room_tundra_iceentrance)
	room_goto(room_tundra_poffzone)
if (room == room_tundra_poffzone)
	room_goto(room_tundra_iceentrance)
if (room == room_water11)
	room_goto(room_water12)
if (room == room_water12)
	room_goto(room_water11)
if (room == room_water_bird)
	room_goto(room_water_prebird)
if (room == room_water_prebird)
	room_goto(room_water_bird)
if (room == room_water_friendlyhub)
	room_goto(room_water_bird)
if (room == room_fire_walkandbranch2)
	room_goto(room_fire_savepoint2)
if (room == room_fire_savepoint2)
	room_goto(room_fire_walkandbranch2)
if (room == room_fire_hotelfront_1)
	room_goto(room_fire_elevator_r3)
if (room == room_fire_elevator_r3)
	room_goto(room_fire_hotelfront_1)
if (room == room_fire_hotelfront_2)
	room_goto(room_shop3)
if (room == room_fire_shootguy_5)
	room_goto(room_fire_core_left)
if (room == room_fire_core_left)
	room_goto(room_fire_shootguy_5)
if (room == room_fire_core_branch)
	room_goto(room_fire_core_center)
if (room == room_fire_core_center)
	room_goto(room_fire_core_branch)
if (room == room_fire_core_topleft)
	room_goto(room_fire_core_treasureleft)
if (room == room_fire_core_topright)
	room_goto(room_fire_core_treasureright)
if (room == room_fire_core_treasureleft)
	room_goto(room_fire_core_topleft)
if (room == room_fire_core_treasureright)
	room_goto(room_fire_core_topright)
if (room == room_fire_core_top)
	room_goto(room_fire_core_warrior)
if (room == room_fire_core_warrior)
	room_goto(room_fire_core_top)
if (room == room_fire_core_right)
	room_goto(room_fire_core_bridge)
if (room == room_fire_core_bridge)
	room_goto(room_fire_core_right)
if (room == room_water_fakehallway)
	room_goto(room_water_savepoint1)
if (room == room_water11)
	room_goto(room_water_savepoint1)
if (room == room_water_savepoint1)
{
	gox = 0
	fsx = 0
	if (FL_Fun == 66)
	{
		if ossafe_file_exists("undertale.ini")
		{
			ossafe_ini_open("undertale.ini")
			fsx = ini_read_real("General", "fun", 0)
			var dosave = 0
			if (fsx == 66 && FL_Fun == 66)
			{
				gox = 1
				FL_Fun = 0
				ini_write_real("General", "fun", 0)
				dosave = 1
			}
			ossafe_ini_close()
			ossafe_savedata_save()
		}
	}
	if (gox == 1)
		room_goto(room_water_fakehallway)
	if (gox == 0)
		room_goto(room_water11)
}
