image_xscale = 2
image_yscale = 2
image_speed = 0.1
y = ((global.idealborder[3] - sprite_height) + 15)
x = ((global.idealborder[1] - sprite_width) + 19)
con = 0
hspeed = -1
shake = 0
nowx = 0
nowy = 0
