speed = 0
direction = 0
first = 30
col = 0
zap = 1
alarm[0] = 20
x = obj_heart.x
y = obj_heart.y
dirr = random(360)
alarm[1] = 1
visible = false
dmg = 8
active = false
king = obj_glowparticle_1 // Daniela: decompiler error, fix this
time = 0
heal = 0
star = 0
FL_UnusedMadjickSoundHandle = 0
