darkify = 1
pseudodarker = instance_create(-20, -20, obj_npc_marker)
pseudodarker.visible = true
pseudodarker.image_speed = 0
pseudodarker.sprite_index = spr_pixblk
pseudodarker.depth = 2
pseudodarker.image_alpha = 0
pseudodarker.image_xscale = 600
pseudodarker.image_yscale = 600
