image_xscale = 2
image_yscale = 2
image_speed = 0
y = ((global.idealborder[3] - sprite_height) + 15)
x = ((global.idealborder[1] - sprite_width) + 19)
walking = false
shake = 2
nowy = y
nowx = x
alarm[5] = 30
trueindex = 5
active = false
atimer = 0
dmg = 9
