noarm = 1
fallarml = instance_create(((x + 36) + sin((siner / 3.5))), (((y - legh) + 80) + (cos((siner / 3.5)) * 2)), obj_fallofflimb)
fallarml.image_xscale = 2
fallarml.image_yscale = 2
fallarml.sprite_index = armlsprite
fallarmr = instance_create(((x + 110) + sin((siner / 3.5))), (((y - legh) + 80) + (cos((siner / 3.5)) * 2)), obj_fallofflimb)
fallarmr.image_xscale = -2
fallarmr.image_yscale = 2
fallarmr.sprite_index = armrsprite
