con = 0
timer = 0
s_offset = 40
o_o = 0
smear = 0
dontdraw = 0
flip = 1
alarm[0] = 1
visible = false
if (instance_find(object_index, 0) == id)
    flip = 0
relx = (x - obj_asriel_swordmaster.x)
sm = obj_asriel_swordmaster
skip = false
twinkle = 0
shake = 0
blazing = 0
bl_o = 0
king = obj_asriel_body
depth = (king.depth + 1)
start = 1
image_alpha = 0
image_xscale = 2
image_yscale = 2
alarm[1] = 2
col = 0
h_mode = 0
