blue = 1
dmg = 7
rate = global.firingrate
alarm[0] = rate
longnote = 0
direction = 0
alarm[0] = 6
turn = 5
green = (-1 + random(6))
cleaner = 0
backwards = 0
sum = scr_monstersum()
siner = random(30)
siner2 = random(30)
