blcon = instance_create(((x + sprite_width) - 8), (ystart + 8), obj_blconsm)
mycommand = round(random(100))
if (mycommand >= 0 && mycommand < 20)
    global.msg[0] = scr_gettext("obj_loox_197")
if (mycommand >= 20 && mycommand < 40)
    global.msg[0] = scr_gettext("obj_loox_198")
if (mycommand >= 40 && mycommand < 60)
    global.msg[0] = scr_gettext("obj_loox_199")
if (mycommand >= 60 && mycommand <= 80)
    global.msg[0] = scr_gettext("obj_loox_200")
if (mycommand >= 80 && mycommand <= 100)
    global.msg[0] = scr_gettext("obj_loox_201")
if (global.turn == 0)
    global.msg[0] = scr_gettext("obj_loox_202")
if (whatiheard == 1)
    global.msg[0] = scr_gettext("obj_loox_205")
if (whatiheard == 3)
    global.msg[0] = scr_gettext("obj_loox_209")
global.msg[1] = scr_gettext("obj_loox_213")
global.typer = 2
blconwd = instance_create((blcon.x + 15), (blcon.y + 10), OBJ_NOMSCWRITER)
global.border = 6
obj_heart.x = (round(((global.idealborder[0] + global.idealborder[1]) / 2)) - 8)
obj_heart.y = (round(((global.idealborder[2] + global.idealborder[3]) / 2)) - 8)
