draw_sprite(sprite_index, 0, x, y)
animimg += 0.25
depth = (50000 - (y * 10))
if (arm == 0)
    draw_sprite(spr_metthand_clasped, animimg, ((x - 19) + xoff), ((y - 26) + yoff))
if (arm == 1)
    draw_sprite(spr_metthand_broad, animimg, ((x - 19) + xoff), (((y - 26) - 8) + yoff))
if (arm == 2)
    draw_sprite(spr_metthand_tragedy, animimg, (((x - 19) - 10) + xoff), (((y - 26) - 10) + yoff))
if (arm == 3)
    draw_sprite(spr_metthand_cry, animimg, ((x - 19) + xoff), (((y - 26) - 10) + yoff))
if (arm == 4)
    draw_sprite(spr_metthand_facescratch, animimg, (((x - 19) - 5) + xoff), (((y - 26) - 9) + yoff))
if (arm == 5)
    draw_sprite(spr_metthand_shrug, animimg, (((x - 19) - 18) + xoff), (((y - 26) - 5) + yoff))
if (arm == 6)
    draw_sprite(spr_metthand_nailfile, animimg, (((x - 19) - 1) + xoff), (((y - 26) + 4) + yoff))
if (arm == 7)
    draw_sprite(spr_metthand_nailfile2, animimg, (((x - 19) - 1) + xoff), (((y - 26) + 1) + yoff))
if (arm == 8)
    draw_sprite(spr_metthand_up, animimg, (((x - 19) - 14) + xoff), (((y - 26) - 11) + yoff))
if (arm == 9)
    draw_sprite(spr_metthand_headpat, animimg, (((x - 19) - 17) + xoff), (((y - 26) - 7) + yoff))
if (arm == 10)
    draw_sprite(spr_metthand_assrummage, animimg, (((x - 19) - 14) + xoff), (((y - 26) - 8) + yoff))
if (arm == 11)
    draw_sprite(spr_metthand_telething, animimg, (((x - 19) - 14) + xoff), (((y - 26) - 11) + yoff))
if (arm == 12)
    draw_sprite(spr_metthand_telepoke, 2, (((x - 19) - 14) + xoff), (((y - 26) - 11) + yoff))
