scr_monstersetup(0, 0, 0, 0, 0)
image_speed = 0
part1 = obj_greatdogbody
mypart1 = instance_create(x, y, part1)
hurtanim = 0
hurtsound = snd_ehurt1
talked = false
whatiheard = -1
attacked = 0
killed = 0
global.heard = 0
takedamage = 0
mercymod = -25
dogignore = 0
close = 0
pet = 0
global.sp = 4
ht = 200
wd = 200
