direction = point_direction(x, y, (obj_heart.x + 8), (obj_heart.y + 8))
image_angle = direction
image_angle += ((x - obj_heart.x) / 2)
direction = image_angle
siner = random(360)
image_xscale = 2
image_yscale = 2
overall = 0
dmg = 8
