global.msg[0] = scr_gettext("obj_pyrope_266")
blcon = instance_create((x + 110), y, obj_blconsm)
gg = floor(random(3))
mycommand = round(random(100))
if (mycommand >= 0 && mycommand < 25)
	global.msg[0] = scr_gettext("obj_pyrope_270")
if (mycommand >= 25 && mycommand < 50)
	global.msg[0] = scr_gettext("obj_pyrope_271")
if (mycommand >= 50 && mycommand < 75)
	global.msg[0] = scr_gettext("obj_pyrope_272")
if (mycommand >= 75 && mycommand < 100)
	global.msg[0] = scr_gettext("obj_pyrope_273")
if (whatiheard == 1)
	global.msg[0] = scr_gettext("obj_pyrope_280")
if (whatiheard == 3)
	global.msg[0] = scr_gettext("obj_pyrope_285")
if (whatiheard == 4)
	global.msg[0] = scr_gettext("obj_pyrope_289")
global.msg[1] = scr_gettext("obj_pyrope_294")
global.typer = 2
blconwd = instance_create((blcon.x + 15), (blcon.y + 10), OBJ_NOMSCWRITER)
global.border = 17
obj_heart.x = (round(((global.idealborder[0] + global.idealborder[1]) / 2)) - 8)
obj_heart.y = (round(((global.idealborder[2] + global.idealborder[3]) / 2)) - 8)
