image_speed = 0.2
initx = x
inity = y
siner = 0
sinerfactor = 64
x = (initx + (sin(degtorad(siner)) * sinerfactor))
y = (inity + (cos(degtorad(siner)) * sinerfactor))
image_angle = (siner + 90)
siner2 = 0
dmg = 0
green = 0
s2factor = 1
sineradd = 4
