blcon = instance_create((x + 95), (y - 25), obj_blconsm)
gg = floor(random(3))
mycommand = round(random(100))
global.msg[0] = scr_gettext("obj_shyren_274")
if (mycommand >= 50)
    global.msg[0] = scr_gettext("obj_shyren_275")
if (encourage == 1)
    global.msg[0] = scr_gettext("obj_shyren_278")
if (encourage == 2)
    global.msg[0] = scr_gettext("obj_shyren_279")
if (encourage == 3)
    global.msg[0] = scr_gettext("obj_shyren_280")
if (encourage == 4)
    global.msg[0] = scr_gettext("obj_shyren_281")
if (encourage == 5)
    global.msg[0] = scr_gettext("obj_shyren_282")
global.msg[1] = scr_gettext("obj_shyren_283")
global.typer = 2
blconwd = instance_create((blcon.x + 15), (blcon.y + 10), OBJ_NOMSCWRITER)
global.border = 6
obj_heart.x = (round(((global.idealborder[0] + global.idealborder[1]) / 2)) - 8)
obj_heart.y = (round(((global.idealborder[2] + global.idealborder[3]) / 2)) - 8)
