con = 0
alarm[4] = 10
image_speed = 0
image_xscale = 3
image_yscale = 3
y = ((global.idealborder[3] - sprite_height) - 2)
x = (global.idealborder[1] - sprite_width)
shake = 0
nowx = x
nowy = y
dmg = 9
