if (draw == 1)
{
	var offset = (global.language == "en" ? 0 : 20)
	draw_set_color(c_white)
	draw_rectangle((64 - offset), 104, (256 + offset), 196, false)
	draw_set_color(c_black)
	draw_rectangle((68 - offset), 108, (252 + offset), 192, false)
	draw_set_color(c_white)
	scr_setfont(fnt_maintext)
	for (i = 0; i < 4; i += 1)
	{
		draw_set_color(c_white)
		if (coord == i)
		{
			draw_set_color(c_yellow)
			draw_sprite(spr_ds3_selectiontriangle, 0, ((84 + (10 * i)) - offset), 152)
			draw_sprite(spr_ds3_selectiontriangle, 1, ((84 + (10 * i)) - offset), 171)
		}
		if (mincoord > i)
			draw_set_color(c_dkgray)
		draw_text(((86 + (10 * i)) - offset), 156, string_hash_to_newline(digit[i]))
	}
	draw_set_color(c_white)
	draw_text_transformed((126 - offset), 156, string_hash_to_newline(scr_gettext("obj_ds3_numberpicker_0")), 0.5, 1, 0)
	if (coord == 4)
		draw_set_color(c_yellow)
	draw_text((156 - offset), 156, string_hash_to_newline(scr_gettext("obj_ds3_numberpicker_1")))
	draw_set_color(c_white)
	if (coord == 5)
		draw_set_color(c_yellow)
	draw_text((210 + (offset * 0.25)), 156, string_hash_to_newline(scr_gettext("obj_ds3_numberpicker_2")))
	draw_set_color(c_gray)
	scr_drawtext_icons((84 - offset), 130, scr_gettext("obj_ds3_numberpicker_3"))
	draw_text((84 - offset), 115, (scr_gettext("obj_ds3_numberpicker_4") + string(FL_DogShrineXboxCoins)))
	givenamount = string(FL_DogShrineXboxDonatedCoins)
	if (givenamount >= 500)
		givenamount = scr_gettext("obj_ds3_numberpicker_5")
	var givenoffset = (global.language == "en" ? 170 : 165)
	draw_text((givenoffset + (offset * 0.25)), 115, (scr_gettext("obj_ds3_numberpicker_6") + givenamount))
	if (coord == 0)
		draw_sprite(spr_heartsmall, 0, (84 - offset), 180)
	if (coord == 1)
		draw_sprite(spr_heartsmall, 0, (94 - offset), 180)
	if (coord == 2)
		draw_sprite(spr_heartsmall, 0, (104 - offset), 180)
	if (coord == 3)
		draw_sprite(spr_heartsmall, 0, (114 - offset), 180)
	var kifuoffset = (global.language == "en" ? 172 : 179)
	if (coord == 4)
		draw_sprite(spr_heartsmall, 0, (kifuoffset - offset), 174)
	var yameoffset = (global.language == "en" ? 218 : 228)
	if (coord == 5)
		draw_sprite(spr_heartsmall, 0, (yameoffset + (offset * 0.25)), 174)
}
