hspeed = -4
siner = 0
counter = 0
counter = (-floor(random(35)))
type = 0
con = 0
image_index = 0
image_speed = 0
image_angle = 270
y = (room_height - (sprite_height * 0.6))
sprite_index = scr_getsprite(sprite_index)
