draw_sprite(sprite_index, image_index, x, y)
if (global.osflavor <= OSFlavors.Mac)
    draw_sprite(scr_getsprite(spr_pxquit), 0, 44, 27)
draw_sprite(spr_neutralpbutton, 0, 43, 58)
draw_sprite(spr_leftpbutton, 0, 54, 58)
draw_sprite(spr_downpbutton, 0, 70, 55)
draw_sprite(spr_rightpbutton, 0, 81, 58)
draw_sprite(spr_uppbutton, 0, 97, 55)
