dingusvol = 0.5
dongusvol = 0
dingus = caster_load("music/menu1.ogg")
dangus = caster_load("music/menu2.ogg")
dongus = caster_load("music/menu3.ogg")
dungus = caster_load("music/menu4.ogg")
caster_loop(dingus, 1, 1)
caster_loop(dangus, 0, 1)
caster_loop(dongus, 0, 1)
caster_loop(dungus, 0, 1)
