draw_set_color(c_black)
ossafe_fill_rectangle(35, 26, (surface_get_width(application_surface) - 35), (surface_get_height(application_surface) - 26))
draw_set_color(c_white)
if (global.language == "en")
{
	old_halign = draw_get_halign()
	old_font = draw_get_font()
	old_color = draw_get_color()
	old_alpha = draw_get_alpha()
	draw_set_halign(fa_center)
	draw_set_font(fnt_main)
	draw_set_color(c_white)
	draw_text_transformed(xx, yy, main_message, 1.5, 1.5, 0)
	draw_text_transformed(xx, y, sub_message_1, 1, 1, 0)
	draw_text_transformed(xx, (y + 85), sub_message_2, 0.75, 0.75, 0)
	draw_text_transformed(xx, (y + 160), sub_message_3, 0.5, 0.5, 0)
	draw_sprite(spr_heart, 0, (xx - 30), (y + 204))
	draw_set_color(c_yellow)
	draw_text_transformed((xx + 10), (y + 200), "OK", 0.75, 0.75, 0)
	draw_set_color(c_white)
	draw_set_alpha(old_alpha)
	draw_set_halign(old_halign)
	draw_set_font(old_font)
	draw_set_color(old_color)
}
else
	draw_sprite_stretched(spr_xbox_jp_account, 0, 0, 0, view_wport[0], view_hport[0])
