myinteract = 3
global.msc = 0
global.typer = 5
global.facechoice = 0
global.faceemotion = 0
global.msg[0] = scr_gettext("obj_readable_modernbook_59")
global.msg[0] = scr_gettext("obj_readable_modernbook_60")
global.msg[1] = scr_gettext("obj_readable_modernbook_61")
global.msg[2] = scr_gettext("obj_readable_modernbook_62")
global.msg[3] = scr_gettext("obj_readable_modernbook_63")
read += 1
if (scr_murderlv() >= 7)
    global.msg[0] = scr_gettext("obj_readable_modernbook_68")
mydialoguer = instance_create(0, 0, obj_dialoguer)
