global.entrance = 20
instance_create(0, 0, obj_persistentfader)
if (room == room_tundra_town)
    room_goto(room_tundra_inn)
if (room == room_tundra_inn)
    room_goto(room_tundra_town)
if (room == room_water11)
    room_goto(room_water_bird)
if (room == room_water12)
    room_goto(room_water_bird)
if (room == room_water_bird)
    room_goto(room_water11)
if (room == room_water14)
    room_goto(room_water_statue)
if (room == room_water_statue)
    room_goto(room_water14)
if (room == room_water_friendlyhub)
    room_goto(room_water_shop)
if (room == room_water_shop)
    room_goto(room_water_friendlyhub)
if (room == room_fire7)
    room_goto(room_fire_turn)
if (room == room_fire10)
    room_goto(room_fire_walkandbranch)
if (room == room_fire_walkandbranch)
    room_goto(room_fire10)
if (room == room_fire_turn)
    room_goto(room_fire7)
if (room == room_fire_savepoint1)
    room_goto(room_fire7)
if (room == room_fire_walkandbranch2)
    room_goto(room_fire_preshootguy4)
if (room == room_fire_preshootguy4)
    room_goto(room_fire_walkandbranch2)
if (room == room_truelab_hub)
    room_goto(room_truelab_prebed)
if (room == room_truelab_prebed)
    room_goto(room_truelab_hub)
if (room == room_truelab_bedroom)
    room_goto(room_truelab_hall3)
if (room == room_truelab_hall3)
    room_goto(room_truelab_bedroom)
if (room == room_fire_prelab)
    room_goto(room_fire_elevator_l1)
if (room == room_fire_elevator_l1)
    room_goto(room_fire_prelab)
if (room == room_tundra_sansroom)
    room_goto(room_tundra_sanshouse)
if (room == room_tundra_sansroom_dark)
    room_goto(room_tundra_sanshouse)
if (room == room_tundra_sanshouse)
{
    if (FL_GotSansRoomKey <= 1)
        room_goto(room_tundra_sansroom_dark)
    else
        room_goto(room_tundra_sansroom)
}
