FL_EncounteredGlyde = 1
scr_monstersetup()
image_speed = 0
part1 = obj_glyde_body
mypart1 = instance_create((x + 72), (y + 24), part1)
alarm[9] = 8
hurtanim = 0
hurtsound = snd_hurtbeef
talked = false
whatiheard = -1
attacked = 0
killed = 0
global.heard = 0
takedamage = 0
mercymod = -50
sha = 0
shb = 0
ht = 200
wd = 240
applaud = 0
nothing = 0
boo = 0
