instance_create(240, 116, obj_mettb_body)
obj_mettb_body.myblend = c_black
obj_mettb_body.myalpha = 0
obj_mettb_body.sineron = 0
obj_mettb_body.depth = -1000
con = 0
cloud = 0
cltimer = 0
otr = 0
flasher = 0
flashamt = 0
blacker = 1
global.batmusic = caster_load("music/mettaton_ex.ogg")
presong = caster_load("music/mettaton_pretransform.ogg")
flashsound = caster_load("music/create.ogg")
x = 200
