bb = 0
thisy = y
thisx = x
image_speed = 0
image_xscale = 2
image_yscale = 2
type = 0
lock = 0
home = 0
txspeed = 0
tyspeed = 0
l_timer = 0
flash = false
meter = 0
metercounter = 0
unhinge = 0
blast = 0
con = 0
ctimer = 0
image_alpha = 0
alarm[6] = 30
relx = (x - obj_asriel_body.x)
rely = (y - obj_asriel_body.y)
king = obj_asriel_body
ks = 0
image_angle = (point_direction(x, y, (obj_heart.x + 8), (obj_heart.y + 8)) + 90)
col_o = 0
sfx_b = caster_load("music/sfx/sfx_a_bullet.ogg")
sfx_t = caster_load("music/sfx/sfx_a_target.ogg")
sfx_l = caster_load("music/sfx/sfx_rainbowbeam_1.ogg")
sfx_p = caster_load("music/sfx/sfx_segapower.ogg")
h_mode = 0
jr = random(360)
